### ISSUE TITLE
Error-Code: 400 Error-Description: There was an error parsing the key for validity

### ISSUE THREAD

**Issue by onderweg** [jamiebicknell/Growl-GNTP#2]
When making GNTP requests (register/notify), I get the following error:

```
Error-Code: 400 Error-Description: There was an error parsing the key for validity 
```

**Comment by onderweg** [comment]
Found a solution: add a space between key hash and <CRLF>:

For example, change following line from:

``` php
$data  = 'GNTP/1.0 REGISTER NONE ' . $this->createHash() . "\r\n";
```

to

``` php
$data  = 'GNTP/1.0 REGISTER NONE ' . $this->createHash() . " \r\n";
```

**Comment by jamiebicknell** [comment]
It's been a while since I've had Growl installed, so I'll need to set this up again and run some tests. I don't see any reason why a space after the hash fixes it as accordingly the the GNTP documentation it's not needed. The only thing I can think of off the top of my head is that `$this->createHash()` wasn't returning a valid hash.

**Comment by jamiebicknell** [comment]
I've been unable to replicate this issue, could you share your OS and version of where this error showed?
